# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"

#locale: "en-US"
title: "SkyThrow"
title_separator: "-"
subtitle: "bluesky posting only client"
description: >- # this means to ignore newlines until "baseurl:"
  「SkyThrow」は投稿専用のblueskyクライアントです。
  iOS版を現在リリース準備中です。
  "SkyThrow" is a bluesky client for posting only.
  The iOS version is currently being prepared for release.
url: "https://hidea.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/skythrow" # the subpath of your site, e.g. /blog
repository: "hidea/skythrow" # GitHub username/repo-name of your site
teaser: "/assets/images/500x300.png"
logo: "/assets/images/88x88.png"

# Social Sharing
twitter:
  username               :
og_image: "/assets/images/1200x630.png"

author:
  name: "SkyThrow"
  avatar: "/assets/images/88x88.png"
  bio: >-
    "SkyThrow" is a bluesky client for posting only. The iOS ver. is currently being prepared for release.
    「SkyThrow」は投稿専用のblueskyクライアントです。現在、iOS版をリリース準備中。<br>
  location: "Chiba,Japan"
  links:
    - label: "bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/skythrow.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hidea"

footer:
  links:
    - label: "bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/skythrow.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hidea"
    - label: "Privacy Policy"
      icon: "fas fa-fw fa-file-alt"
      url: "/privacy-policy/"
    - label: "Terms of Service"
      icon: "fas fa-fw fa-file-alt"
      url: "/tos/"

include:
  - .htaccess
  - _pages
  - _helpdocs

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true

timezone: Asia/Tokyo

plugins:
  - jekyll-feed
  - jekyll-include-cache


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
